# Site settings
title: No Name Blog | Ramblings in the rural American West
email: mschmidty@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
  Everything from my perspective in America.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mjschmidty  
github_username:  mschmidt

# Build settings
markdown: kramdown
